spring.application.name=api-gateway
server.port=8084
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

spring.cloud.gateway.server.webmvc.routes[0].id=USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/user/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api/v1/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[1].id=ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v2/order/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api/v2/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[2].id=PRODUCTS-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PRODUCTS-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v3/products/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api/v3/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[3].id=SHOP-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://SHOP-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v4/shop/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RewritePath=/api/v4/(?<segment>.*), /${segment}